- name: Verificar si el servicio ssh esta corriendo en el nodo
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: verificar que apache siempre este arriba
      service:
        name: apache2
        state: started
        enabled: yes
